### ISSUE TITLE
case sensitivity of property metadata and selectors in push notifications yaml causes generate to fail

### ISSUE THREAD

**Issue by patrick-huber-pivotal** [pivotalservices/tile-config-generator#2]
It looks like the property metadata filter in (generator/property_metadata.go) should be case insensitive. 

```go
func (p *PropertyMetadata) SelectorMetadata(selector string) ([]PropertyMetadata, error) {
	var options []string
	for _, optionTemplate := range p.OptionTemplates {
		options = append(options, optionTemplate.Name)
		if selector == optionTemplate.Name {
			return optionTemplate.PropertyMetadata, nil
		}
	}
	return nil, fmt.Errorf("Option template not found for selector %s options include %v", selector, options)
}
```

changing it to a case insensitive comparison would fix this. (I realize the tile developer probably needs to be more consistent, but I don't see an issue with this change from a anti-fragility perspective)

```go
func (p *PropertyMetadata) SelectorMetadata(selector string) ([]PropertyMetadata, error) {
	var options []string
	for _, optionTemplate := range p.OptionTemplates {
		options = append(options, optionTemplate.Name)
		if strings.EqualFold(selector, optionTemplate.Name) {
			return optionTemplate.PropertyMetadata, nil
		}
	}
	return nil, fmt.Errorf("Option template not found for selector %s options include %v", selector, options)
}
```

## Reproduction

Using tile version: 1.10.0
[api link](https://network.pivotal.io/api/v2/products/push-notification-service/releases/114883/product_files/155025/download)

> p_push_notifications.yml

```yaml
- name: deployment_type
  type: selector
  configurable: true
  default: Production
  option_templates:
  - name: development
    select_value: Development
    named_manifests:
    - name: push_deployment_snippet
      manifest: |
        push_api_instance_count: 1
        push_dashboard_instance_count: 1
        push_analytics_instance_count: 1
        push_broker_instance_count: 1
        push_scheduler_instance_count: 1
  - name: production
    select_value: Production
    named_manifests:
    - name: push_deployment_snippet
      manifest: |
        push_api_instance_count: 2
        push_dashboard_instance_count: 2
        push_analytics_instance_count: 2
        push_broker_instance_count: 2
        push_scheduler_instance_count: 2
```

> command

```bash
$ tile-config-generator generate --pivotal-file-path=/mnt/c/Users/patri/Downloads/p-push-notifications-1.10.0-build.8.pivotal --base-directory=/tmp/p-push-notifications --do-not-include-product-version
```

> output

```
error: Option template not found for selector Production options include [development production custom]
```
