### ISSUE TITLE
Non-configurable properties cannot be configured

### ISSUE THREAD

**Issue by ramonskie** [pivotalservices/tile-config-generator#24]
when running the following comand to generate the tile config files

` tile-config-generator generate --token=MYOTKEN --product-slug=elastic-runtime --product-version=2.5.4 --product-glob='srt*.pivotal' --include-errands --do-not-include-product-version --base-directory=templates/assets/tiles/srt`

the following file is created `features/credhub_database-external.yml`
with contains this non-configurable property
```
 - type: replace
   path: /product-properties/.properties.credhub_database.external.require_tls?
   value:
     value: ((credhub_database/external/require_tls))
```
